---
name: "Actions for Discord"
description: "Outputs a message to Discord"
author: RoutedBits
branding:
  icon: message-square
  color: gray-dark

inputs:
  msg:
    description: 'The message to display in the Discord message.'
    required: true

runs:
  using: composite
  steps:
    - run: >
        curl -X POST
        -H "Content-Type: application/json"
        --data "{\"content\": \"${{ inputs.msg }}\"}"
        $DISCORD_WEBHOOK
      shell: bash
